Add missing headers reported by `gcc-13`
Without the change the build fails against `gcc-13` as:

    gimx.c:587:3: error: incompatible implicit declaration
        of built-in function 'free' [-Werror=builtin-declaration-mismatch]
      587 |   free(gimx_params.homedir);
          |   ^~~~