controller.c: fix `adapter_detect()` prototype consistency
WIthout the change the build of `gcc-13` fails as:

    controller.c:922:15: error: conflicting types for 'adapter_detect'
      due to enum/integer mismatch; have 'e_gimx_status()' [-Werror=enum-int-mismatch]
      922 | e_gimx_status adapter_detect()
          |               ^~~~~~~~~~~~~~